efcoreApp/Models/ErrorViewModel.cs
namespace efcoreApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

efcoreApp/Controllers/CourseController.cs
using System.Threading.Tasks;
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace efcoreApp.Controllers
{
    public class CourseController : Controller
    {
        private readonly DataContext _context;

        public CourseController(DataContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var courses = _context.Courses.ToList();
            return View(courses);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Course course)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Courses.Add(course);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    throw;
                }
            }
            return View(course);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var course = _context.Courses.Find(id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }


        [HttpPost]
        public IActionResult Edit(int id, Course model)
        {
            var course = _context.Courses.Find(id);

            if (course == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    course.CourseTitle = model.CourseTitle;
                    _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "An error occurred while updating the course.");
                    return View(model);
                }
            }

            return View(model);

        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var course = _context.Courses.Find(id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id, Course? model)
        {
            var course = _context.Courses.Find(id);

            if (course == null)
            {
                return NotFound();
            }

            try
            {
                _context.Courses.Remove(course);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "An error occurred while updating the course.");
                return View(model);
            }

        }

    }
}

efcoreApp/Controllers/CourseEnrollmentController.cs
using System.Threading.Tasks;
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class CourseEnrollmentController : Controller
    {
        private readonly DataContext _context;
        public CourseEnrollmentController(DataContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Courses = new SelectList(await _context.Courses.ToListAsync(),"CourseId","CourseTitle");
            ViewBag.Students = new SelectList(await _context.Students.ToListAsync(), "StudentId", "FirstName");
            return View();
        }

        public IActionResult Enroll(){
            return View();
        }
    }
}

efcoreApp/Controllers/StudentController.cs
using System.Threading.Tasks;
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace efcoreApp.Controllers
{
    public class StudentController : Controller
    {
        private readonly DataContext _context;

        public StudentController(DataContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var students = _context.Students.ToList();
            return View(students);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Student student)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Students.Add(student);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (System.Exception)
                {
                    throw;
                }
            }

            return View(student);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var student = await _context.Students.FindAsync(id);
            // var student = await _context.Students.FirstOrDefaultAsync(x => x.StudentId == id); // Bu şekilde de yapılabilir. Bu şekilde farklı kolonlar üzerinden de arama yapılabilir.

            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Student model)
        {
            var student = await _context.Students.FindAsync(id);

            if (student == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    student.FirstName = model.FirstName;
                    student.LastName = model.LastName;
                    student.Email = model.Email;
                    student.PhoneNumber = model.PhoneNumber;
                    student.BirthTime = model.BirthTime;
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "An error occurred while updating the student.");
                    return View(model);
                }
            }

            return View(student);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            var student = await _context.Students.FindAsync(id);
            // var student = await _context.Students.FirstOrDefaultAsync(x => x.StudentId == id); // Bu şekilde de yapılabilir. Bu şekilde farklı kolonlar üzerinden de arama yapılabilir.

            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id, Student? model)
        {
            var student = await _context.Students.FindAsync(id);

            if (student == null)
            {
                return NotFound();
            }

            try
            {
                _context.Students.Remove(student);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "An error occurred while updating the student.");
                return View(model);
            }
        }
    }
}

efcoreApp/Views/Course/Create.cshtml
@model Course

@{
ViewData["Title"] = "Create a new course";
}

<div class="card">
    <div class="card-header">
        <h4>Create a new course</h4>
        <p>Fill in the form below to create a new course</p>
    </div>
    <div class="card-body">
        <form asp-controller="Course" asp-action="Create" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group my-2">
                <label asp-for="CourseTitle" class="form-label">Course name</label>
                <input asp-for="CourseTitle" class="form-control" placeholder="Enter a valid name">
            </div>
            <div class="form-group mt-4">
                <a asp-controller="Course" asp-action="Index" class="btn btn-secondary">Back to list</a>
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>
    </div>
</div>

efcoreApp/Views/Course/Delete.cshtml
@model Course

@{
ViewData["Title"] = "Delete course";
}

<div class="card">
    <div class="card-header">
        <p>
            Are you sure you want to delete the
            <b>
                @Model.CourseTitle
            </b>
            with the following details?
        </p>
    </div>
    <div class="card-body">
        <form method="post" asp-controller="Course" asp-action="Delete">
            <input type="hidden" asp-for="CourseId" />
            <a class="btn btn-secondary" asp-controller="Course" asp-action="Index">Back to List</a>
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>

efcoreApp/Views/Course/Edit.cshtml
@model Course

@{
ViewData["Title"] = "Edit course";
}

<div class="card">
    <div class="card-header">
        <h4>Edit an already course</h4>
        <p>Fill in the form below to edit a already course</p>
    </div>
    <div class="card-body">
        <form asp-controller="Course" asp-action="Edit" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="CourseId">
            <div class="form-group my-2">
                <label asp-for="CourseTitle" class="form-label">Course name</label>
                <input asp-for="CourseTitle" class="form-control" placeholder="Enter a valid name">
            </div>
            <div class="form-group mt-4">
                <a asp-controller="Course" asp-action="Index" class="btn btn-secondary">Back to list</a>
                <button class="btn btn-warning" type="submit">Edit</button>
            </div>
        </form>
    </div>
</div>

efcoreApp/Views/Course/Index.cshtml
@model IEnumerable<Course>

@{
ViewData["Title"] = "Course list";
}


<div class="card">
    <div class="card-header">
        <h4>Course list</h4>
        <p>Here is a list of all courses</p>
        <a asp-controller="Course" asp-action="Create" class="btn btn-primary">
            Create a new course
        </a>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.CourseTitle)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var course in Model){
                <tr>
                    <td>@course.CourseTitle</td>
                    <td>
                        <a asp-controller="Course" asp-action="Edit" asp-route-id="@course.CourseId"
                            class="btn btn-warning">
                            Edit
                        </a>
                        <a asp-controller="Course" asp-action="Delete" asp-route-id="@course.CourseId"
                            class="btn btn-danger">
                            Delete
                        </a>
                    </td>
                </tr>
                }

                @if(!Model.Any()){
                <tr>
                    <td colspan="6">
                        <p class="text-center m-0 text-muted">No courses found</p>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

efcoreApp/Views/CourseEnrollment/Index.cshtml
@model CourseEnrollment

@{
ViewData["Title"] = "Enroll in a course";
}


<div class="card">
    <div class="card-header">
        <h4>Enroll in a course</h4>
        <p>Fill in the form below to enroll in a course</p>
    </div>

    <div class="card-body">
        <form asp-controller="CourseEnrollment" asp-action="Enroll" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group my-2">
                <label asp-for="CourseId" class="form-label">Course name</label>
                <select asp-items="ViewBag.Courses" class="form-control"></select>
            </div>
             <div class="form-group my-2">
                <label asp-for="StudentId" class="form-label">Student name</label>
                <select asp-items="ViewBag.Students"  class="form-control"></select>
            </div>
            <div class="form-group my-2">
                <button type="submit" class="btn btn-primary">
                    Enroll
                </button>
            </div>
        </form>
    </div>
</div>

efcoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - efcoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/efcoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Student" asp-action="Index">efcoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CourseEnrollment" asp-action="Index">Course Enrollment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>